# Site settings
title: Ben's Tech Bottega
email: bdrasin@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Ben Drasin's software projects and writings/ruminations on tech.  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bendra.github.io" # the base hostname & protocol for your site
twitter_username: uther_bendragon
github_username:  bendra
linkedin_username: bendrasin


paginate: 5
paginate_path: "page:num"

# Build settings
markdown: kramdown
