# Site settings
title: Benjamin Drasin
email: bdrasin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  One-stop shopping for Ben Drasin's software projects and writings/ruminations on tech.  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bendra.github.io" # the base hostname & protocol for your site
twitter_username: uther_bendragon
github_username:  bendra

# Build settings
markdown: kramdown
